# Generated by Django 3.1.7 on 2021-04-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20210415_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_structural_risk',
            name='business_basic_info_id',
        ),
        migrations.RemoveField(
            model_name='business_structural_risk',
            name='risk_weight_id',
        ),
        migrations.RemoveField(
            model_name='business_systemic_risk',
            name='business_basic_info_id',
        ),
        migrations.RemoveField(
            model_name='business_systemic_risk',
            name='risk_weight_id',
        ),
        migrations.RemoveField(
            model_name='hedgeability',
            name='business_condition_id',
        ),
        migrations.RemoveField(
            model_name='hedgeability',
            name='business_conditional_risk_id',
        ),
        migrations.RemoveField(
            model_name='hedgeability',
            name='business_finance_id',
        ),
        migrations.RemoveField(
            model_name='hedgeability',
            name='business_preference_id',
        ),
        migrations.RemoveField(
            model_name='hedgeability',
            name='business_structural_risk_id',
        ),
        migrations.RemoveField(
            model_name='hedgeability',
            name='business_systemic_risk_id',
        ),
        migrations.DeleteModel(
            name='Business_Conditional_Risk',
        ),
        migrations.DeleteModel(
            name='Business_Structural_Risk',
        ),
        migrations.DeleteModel(
            name='Business_Systemic_Risk',
        ),
        migrations.DeleteModel(
            name='Hedgeability',
        ),
        migrations.DeleteModel(
            name='Risk_Weight',
        ),
    ]
