# Generated by Django 3.1.7 on 2021-04-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20210415_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_basic_info',
            name='address_1',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='business_basic_info',
            name='address_2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='business_basic_info',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='business_basic_info',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='business_basic_info',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='business_basic_info',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='business_basic_info',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='business_basic_info',
            name='sector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business_basic_info',
            name='state',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='business_basic_info',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='business_basic_info',
            name='description_of_business',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='business_basic_info',
            name='number_of_employees',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='business_basic_info',
            name='website',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
