# Generated by Django 3.1.1 on 2021-04-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_Level',
            fields=[
                ('uniqueid', models.IntegerField(primary_key=True, serialize=False)),
                ('row1', models.IntegerField()),
                ('row2', models.IntegerField()),
                ('row3', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Auth_Level',
            },
        ),
    ]
